/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AboutImport } from "./routes/about";
import { Route as AuthenticatedImport } from "./routes/_authenticated";
import { Route as IndexImport } from "./routes/index";
import { Route as StoreIndexImport } from "./routes/Store/index";
import { Route as AuthenticatedProfileImport } from "./routes/_authenticated/profile";
import { Route as AuthenticatedExpensesTrackerIndexImport } from "./routes/_authenticated/ExpensesTracker/index";
import { Route as AuthenticatedStoreEditProductImport } from "./routes/_authenticated/Store/editProduct";
import { Route as AuthenticatedStoreCreateProductImport } from "./routes/_authenticated/Store/createProduct";
import { Route as AuthenticatedStoreCartImport } from "./routes/_authenticated/Store/cart";
import { Route as AuthenticatedExpensesTrackerExpensesImport } from "./routes/_authenticated/ExpensesTracker/expenses";
import { Route as AuthenticatedExpensesTrackerCreateExpenseImport } from "./routes/_authenticated/ExpensesTracker/createExpense";

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const StoreIndexRoute = StoreIndexImport.update({
  id: "/Store/",
  path: "/Store/",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedExpensesTrackerIndexRoute =
  AuthenticatedExpensesTrackerIndexImport.update({
    id: "/ExpensesTracker/",
    path: "/ExpensesTracker/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedStoreEditProductRoute =
  AuthenticatedStoreEditProductImport.update({
    id: "/Store/editProduct",
    path: "/Store/editProduct",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedStoreCreateProductRoute =
  AuthenticatedStoreCreateProductImport.update({
    id: "/Store/createProduct",
    path: "/Store/createProduct",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedStoreCartRoute = AuthenticatedStoreCartImport.update({
  id: "/Store/cart",
  path: "/Store/cart",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedExpensesTrackerExpensesRoute =
  AuthenticatedExpensesTrackerExpensesImport.update({
    id: "/ExpensesTracker/expenses",
    path: "/ExpensesTracker/expenses",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedExpensesTrackerCreateExpenseRoute =
  AuthenticatedExpensesTrackerCreateExpenseImport.update({
    id: "/ExpensesTracker/createExpense",
    path: "/ExpensesTracker/createExpense",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/profile": {
      id: "/_authenticated/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthenticatedProfileImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/Store/": {
      id: "/Store/";
      path: "/Store";
      fullPath: "/Store";
      preLoaderRoute: typeof StoreIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/ExpensesTracker/createExpense": {
      id: "/_authenticated/ExpensesTracker/createExpense";
      path: "/ExpensesTracker/createExpense";
      fullPath: "/ExpensesTracker/createExpense";
      preLoaderRoute: typeof AuthenticatedExpensesTrackerCreateExpenseImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/ExpensesTracker/expenses": {
      id: "/_authenticated/ExpensesTracker/expenses";
      path: "/ExpensesTracker/expenses";
      fullPath: "/ExpensesTracker/expenses";
      preLoaderRoute: typeof AuthenticatedExpensesTrackerExpensesImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/Store/cart": {
      id: "/_authenticated/Store/cart";
      path: "/Store/cart";
      fullPath: "/Store/cart";
      preLoaderRoute: typeof AuthenticatedStoreCartImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/Store/createProduct": {
      id: "/_authenticated/Store/createProduct";
      path: "/Store/createProduct";
      fullPath: "/Store/createProduct";
      preLoaderRoute: typeof AuthenticatedStoreCreateProductImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/Store/editProduct": {
      id: "/_authenticated/Store/editProduct";
      path: "/Store/editProduct";
      fullPath: "/Store/editProduct";
      preLoaderRoute: typeof AuthenticatedStoreEditProductImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/ExpensesTracker/": {
      id: "/_authenticated/ExpensesTracker/";
      path: "/ExpensesTracker";
      fullPath: "/ExpensesTracker";
      preLoaderRoute: typeof AuthenticatedExpensesTrackerIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedExpensesTrackerCreateExpenseRoute: typeof AuthenticatedExpensesTrackerCreateExpenseRoute;
  AuthenticatedExpensesTrackerExpensesRoute: typeof AuthenticatedExpensesTrackerExpensesRoute;
  AuthenticatedStoreCartRoute: typeof AuthenticatedStoreCartRoute;
  AuthenticatedStoreCreateProductRoute: typeof AuthenticatedStoreCreateProductRoute;
  AuthenticatedStoreEditProductRoute: typeof AuthenticatedStoreEditProductRoute;
  AuthenticatedExpensesTrackerIndexRoute: typeof AuthenticatedExpensesTrackerIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedExpensesTrackerCreateExpenseRoute:
    AuthenticatedExpensesTrackerCreateExpenseRoute,
  AuthenticatedExpensesTrackerExpensesRoute:
    AuthenticatedExpensesTrackerExpensesRoute,
  AuthenticatedStoreCartRoute: AuthenticatedStoreCartRoute,
  AuthenticatedStoreCreateProductRoute: AuthenticatedStoreCreateProductRoute,
  AuthenticatedStoreEditProductRoute: AuthenticatedStoreEditProductRoute,
  AuthenticatedExpensesTrackerIndexRoute:
    AuthenticatedExpensesTrackerIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/about": typeof AboutRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/Store": typeof StoreIndexRoute;
  "/ExpensesTracker/createExpense": typeof AuthenticatedExpensesTrackerCreateExpenseRoute;
  "/ExpensesTracker/expenses": typeof AuthenticatedExpensesTrackerExpensesRoute;
  "/Store/cart": typeof AuthenticatedStoreCartRoute;
  "/Store/createProduct": typeof AuthenticatedStoreCreateProductRoute;
  "/Store/editProduct": typeof AuthenticatedStoreEditProductRoute;
  "/ExpensesTracker": typeof AuthenticatedExpensesTrackerIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteWithChildren;
  "/about": typeof AboutRoute;
  "/profile": typeof AuthenticatedProfileRoute;
  "/Store": typeof StoreIndexRoute;
  "/ExpensesTracker/createExpense": typeof AuthenticatedExpensesTrackerCreateExpenseRoute;
  "/ExpensesTracker/expenses": typeof AuthenticatedExpensesTrackerExpensesRoute;
  "/Store/cart": typeof AuthenticatedStoreCartRoute;
  "/Store/createProduct": typeof AuthenticatedStoreCreateProductRoute;
  "/Store/editProduct": typeof AuthenticatedStoreEditProductRoute;
  "/ExpensesTracker": typeof AuthenticatedExpensesTrackerIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/about": typeof AboutRoute;
  "/_authenticated/profile": typeof AuthenticatedProfileRoute;
  "/Store/": typeof StoreIndexRoute;
  "/_authenticated/ExpensesTracker/createExpense": typeof AuthenticatedExpensesTrackerCreateExpenseRoute;
  "/_authenticated/ExpensesTracker/expenses": typeof AuthenticatedExpensesTrackerExpensesRoute;
  "/_authenticated/Store/cart": typeof AuthenticatedStoreCartRoute;
  "/_authenticated/Store/createProduct": typeof AuthenticatedStoreCreateProductRoute;
  "/_authenticated/Store/editProduct": typeof AuthenticatedStoreEditProductRoute;
  "/_authenticated/ExpensesTracker/": typeof AuthenticatedExpensesTrackerIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/about"
    | "/profile"
    | "/Store"
    | "/ExpensesTracker/createExpense"
    | "/ExpensesTracker/expenses"
    | "/Store/cart"
    | "/Store/createProduct"
    | "/Store/editProduct"
    | "/ExpensesTracker";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | ""
    | "/about"
    | "/profile"
    | "/Store"
    | "/ExpensesTracker/createExpense"
    | "/ExpensesTracker/expenses"
    | "/Store/cart"
    | "/Store/createProduct"
    | "/Store/editProduct"
    | "/ExpensesTracker";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/about"
    | "/_authenticated/profile"
    | "/Store/"
    | "/_authenticated/ExpensesTracker/createExpense"
    | "/_authenticated/ExpensesTracker/expenses"
    | "/_authenticated/Store/cart"
    | "/_authenticated/Store/createProduct"
    | "/_authenticated/Store/editProduct"
    | "/_authenticated/ExpensesTracker/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AboutRoute: typeof AboutRoute;
  StoreIndexRoute: typeof StoreIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  StoreIndexRoute: StoreIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/Store/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile",
        "/_authenticated/ExpensesTracker/createExpense",
        "/_authenticated/ExpensesTracker/expenses",
        "/_authenticated/Store/cart",
        "/_authenticated/Store/createProduct",
        "/_authenticated/Store/editProduct",
        "/_authenticated/ExpensesTracker/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/Store/": {
      "filePath": "Store/index.tsx"
    },
    "/_authenticated/ExpensesTracker/createExpense": {
      "filePath": "_authenticated/ExpensesTracker/createExpense.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ExpensesTracker/expenses": {
      "filePath": "_authenticated/ExpensesTracker/expenses.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/Store/cart": {
      "filePath": "_authenticated/Store/cart.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/Store/createProduct": {
      "filePath": "_authenticated/Store/createProduct.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/Store/editProduct": {
      "filePath": "_authenticated/Store/editProduct.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ExpensesTracker/": {
      "filePath": "_authenticated/ExpensesTracker/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
